# Generated by Django 4.1.5 on 2023-01-19 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='sitios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('host', models.CharField(max_length=50)),
                ('api_password', models.CharField(max_length=50)),
                ('api_user', models.CharField(max_length=50)),
            ],
        ),
    ]
